### ISSUE TITLE
Network Policy error

### ISSUE THREAD

**Issue by bstempien** [SAP-samples/btp-kyma-runtime-multitenancy-tutorial#10]
In both the included Deployment YAML here and within the Tutorial text the "Mission - Develop a Node.js Application in the SAP BTP Kyma Runtime/k8s-deployment-backend.yaml" Network Policy contains an error that will prevent access to the application and thus the Tutorial will Fail.
The ingress policy namespaceSelector should be changed to:

```
ingress:
    - from:
        - podSelector:
            matchLabels:
              app: istio-ingressgateway
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
```
By default the istio-system Namespace does not have a label called name. But as of Kubernetes v1.21 there is a immutable label "kubernetes.io/metadata.name" added to every namespace. Thus the update to the Network Policy will allow the Tutorial to work out of the box.
